name: indberet
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.3.0
  firebase_analytics: ^11.3.3
  geolocator: ^13.0.1
  google_maps_flutter: ^2.3.0
  location: ^4.3.0
  shared_preferences: ^2.0.10
  flutter_local_notifications: ^12.0.0
  csv: ^5.0.0
  excel: ^2.0.6
  path_provider: ^2.0.11
  intl: ^0.17.0
  http: ^0.13.5
  flutter_map: ^3.1.0
  latlong2: ^0.8.1
  logger: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
