// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeI48OuE-gt3lY1is2bYla613vbqOr6mM',
    appId: '1:43334541697:web:cdcdd28be548e6803b8880',
    messagingSenderId: '43334541697',
    projectId: 'test-d4f18',
    authDomain: 'test-d4f18.firebaseapp.com',
    storageBucket: 'test-d4f18.firebasestorage.app',
    measurementId: 'G-JLQKL69EZW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC51_XJir66FlyyrJknVvSCeexAIVGRU7k',
    appId: '1:43334541697:android:dd7750a8722c5c9e3b8880',
    messagingSenderId: '43334541697',
    projectId: 'test-d4f18',
    storageBucket: 'test-d4f18.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiRbgK8u82DNudwW6o8rw9U5HlKqDHFNU',
    appId: '1:43334541697:ios:f61787b5896ddf4a3b8880',
    messagingSenderId: '43334541697',
    projectId: 'test-d4f18',
    storageBucket: 'test-d4f18.firebasestorage.app',
    iosClientId: '43334541697-j2eip1k9ac8ij028ispm8mv68vtkfffi.apps.googleusercontent.com',
    iosBundleId: 'com.example.indberet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiRbgK8u82DNudwW6o8rw9U5HlKqDHFNU',
    appId: '1:43334541697:ios:f61787b5896ddf4a3b8880',
    messagingSenderId: '43334541697',
    projectId: 'test-d4f18',
    storageBucket: 'test-d4f18.firebasestorage.app',
    iosClientId: '43334541697-j2eip1k9ac8ij028ispm8mv68vtkfffi.apps.googleusercontent.com',
    iosBundleId: 'com.example.indberet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeI48OuE-gt3lY1is2bYla613vbqOr6mM',
    appId: '1:43334541697:web:804b121062a7f8443b8880',
    messagingSenderId: '43334541697',
    projectId: 'test-d4f18',
    authDomain: 'test-d4f18.firebaseapp.com',
    storageBucket: 'test-d4f18.firebasestorage.app',
    measurementId: 'G-BJZP4MVQGN',
  );
}
